import type { Service } from "@/lib/firestore/types";

export const staticServices: Service[] = [
  {
    id: "cnc-plate-bending",
    title: "CNC Plate Bending",
    tagline: "Press brake plate forming that complements our CNC-cut profiles",
    description:
      "Once plates are profiled on our CNC cutting lines, press brake forming shapes them to the required angles. Program-driven control keeps each bend repeatable, so cut-and-bend parts arrive at fabrication with tight, consistent geometry across heavy industrial runs.",
    image: "/service-bending.png",
    features: [
      "Forming carried out on programmable press brakes",
      "Bend angles held to CNC-controlled tolerances",
      "Identical results from one batch to the next",
      "Handles large panels and heavy plate work",
      "Pairs cleanly with laser and plasma cut blanks",
      "Steady quality throughout production quantities",
    ],
    specs: [
      { label: "Capacity", value: "Up to 10 m length at 12 mm thickness" },
      { label: "Capacity", value: "Up to 6 m length at 25 mm thickness" },
      { label: "Control", value: "CNC press brake" },
      { label: "Use Cases", value: "Large-scale heavy-duty industrial applications" },
    ],
  },
  {
    id: "sheet-metal-shearing-cutting",
    title: "Sheet Metal Shearing Cutting",
    tagline: "Hydraulic straight-line shearing for blanks feeding our cutting lines",
    description:
      "Where a clean straight cut is all a job needs, hydraulic shearing sizes sheets and plates quickly and squarely. It is a cost-effective route for production blanks, strip work, and prepping stock before laser or plasma profiling, with reliable batch-to-batch accuracy.",
    image: "/service-shearing-cutting.png",
    features: [
      "Square straight-line cuts from a hydraulic shear",
      "Handles both sheet and plate job work",
      "Batch sizing to feed production and fabrication",
      "Rapid throughput for cut-to-size stock",
      "Burr-light edges reproduced across every piece",
      "Preps material ahead of profiling and bending",
    ],
    specs: [
      { label: "Thickness", value: "Up to 32 mm" },
      { label: "Length", value: "Up to 5 meter" },
      { label: "Process", value: "Hydraulic shearing cutting" },
      { label: "Use Cases", value: "Cut-to-size sheets, plate blanks, strips, fabrication jobs" },
    ],
  },
  {
    id: "cnc-laser-cutting",
    title: "CNC Laser Cutting",
    tagline: "Precision fiber laser profiling straight from your DXF files",
    description:
      "Our fiber laser system turns CAD drawings into finished parts with sharp edges, tight tolerances, and very little scrap. From single prototypes to repeat runs, it profiles intricate shapes on both standard and oversized sheets across a wide range of industries.",
    image: "/service-cnc.png",
    features: [
      "Fiber laser cutting held to fine tolerances",
      "Crisp edge finish with little wasted material",
      "Quick turnaround on production quantities",
      "Oversized sheets accommodated on a large bed",
      "Ideal for detailed and repeated profiles",
      "Serves a broad spread of industrial sectors",
    ],
    specs: [
      { label: "MS Cutting Capacity", value: "Up to 25 mm" },
      { label: "SS Cutting Capacity", value: "Up to 16 mm" },
      { label: "Bed Size", value: "8000 mm x 2500 mm" },
      { label: "Industries", value: "Construction, automotive, aerospace, heavy machinery, architecture" },
    ],
  },
  {
    id: "plate-rolling",
    title: "Plate Rolling",
    tagline: "Rolling laser and plasma cut plate into curved sections",
    description:
      "Flat plate that has been profiled to size is rolled into smooth, accurate curves for cylinders, cones, and shells. Controlled roll settings keep the radius uniform, delivering formed components ready for the next stage of fabrication.",
    image: "/service-rolling.png",
    features: [
      "Even, accurate curvature from the rolling set",
      "Radius held steady along the full length",
      "Custom rolling diameters on request",
      "Well suited to cylindrical and curved parts",
      "Ready for industrial job-work volumes",
      "Dependable feed into fabrication lines",
    ],
    specs: [
      { label: "Capacity", value: "Up to 2.5 m length at 16 mm thickness" },
      { label: "Focus", value: "Industrial applications" },
      { label: "Output", value: "Rolled curved plate parts" },
      { label: "Process", value: "Plate rolling" },
    ],
  },
  {
    id: "cnc-plasma-cutting",
    title: "CNC Plasma Cutting",
    tagline: "Fast CNC plasma profiling for thick structural plate",
    description:
      "For mild steel and heavier plate, CNC plasma cutting profiles shapes quickly and economically. Driven directly from CAD data, it is a strong fit for structural members, base plates, brackets, and other fabrication-ready parts produced in volume.",
    image: "/service-profile.png",
    features: [
      "Rapid CNC plasma profile cutting",
      "Built for thick plate and structural components",
      "Any shape driven straight from CAD drawings",
      "Fabrication-ready parts off the table",
      "Efficient across industrial production batches",
      "Cuts base plates, brackets, and heavy sections",
    ],
    specs: [
      { label: "Process", value: "CNC plasma profile cutting" },
      { label: "Material", value: "Mild steel and industrial steel plates" },
      { label: "Applications", value: "Base plates, brackets, flanges, structural parts" },
      { label: "Fit", value: "Heavy fabrication and repeat production work" },
    ],
  },
  {
    id: "assembly",
    title: "Assembly",
    tagline: "Bringing cut and formed parts together into finished units",
    description:
      "Components produced across our cutting and forming processes are joined into complete products through welding, riveting, and related techniques. Careful fit-up ties laser and plasma cut parts into ready-to-ship assemblies.",
    image: "/service-base-plates.png",
    features: [
      "Combines parts from several process routes",
      "Joining by welding and riveting",
      "Both sub-assembly and final build handled",
      "Alignment and fit-up checked to drawing",
      "Slots into the wider fabrication workflow",
      "Delivered as complete, finished products",
    ],
    specs: [
      { label: "Process Scope", value: "Welding, riveting, and related assembly methods" },
      { label: "Input", value: "Parts from multiple forming operations" },
      { label: "Output", value: "Finished assemblies" },
      { label: "Use Cases", value: "Industrial fabricated products" },
    ],
  },
  {
    id: "welding",
    title: "Welding",
    tagline: "Joining cut sections into strong, durable structures",
    description:
      "Welding fuses metal parts using heat, pressure, or both, and ties the sections we cut and form into solid structures. It is a core step in sheet metal fabrication, producing joints built to hold under load.",
    image: "/service-welding.png",
    features: [
      "Joining by heat, pressure, or both",
      "Sections tied together for fabrication",
      "Strong, long-lasting welded joints",
      "Handles one-off and production work alike",
      "Weld quality ready for fabrication use",
      "Feeds directly into assembly operations",
    ],
    specs: [
      { label: "Method", value: "Heat, pressure, or combined welding techniques" },
      { label: "Application", value: "Sheet metal fabrication and section joining" },
      { label: "Output", value: "Joined metal structures and components" },
      { label: "Fit", value: "Custom and industrial fabrication jobs" },
    ],
  },
  {
    id: "deep-drawing",
    title: "Deep Drawing",
    tagline: "Drawing flat blanks into deep three-dimensional shapes",
    description:
      "Deep drawing pulls a flat blank over a die to form three-dimensional parts such as cans, pots, and containers. It converts profiled sheet stock into hollow shapes in a repeatable, production-friendly way.",
    image: "/service-deep-drawing.png",
    features: [
      "Sheet drawn over a shaped die",
      "Flat blanks formed into 3D parts",
      "Ideal for container-style geometries",
      "Consistent, repeatable forming cycle",
      "Geared toward mass manufacturing",
      "Handles deep-profile components well",
    ],
    specs: [
      { label: "Process", value: "Deep drawing over die" },
      { label: "Input", value: "Flat sheet metal" },
      { label: "Output", value: "3D formed components" },
      { label: "Common Products", value: "Cans, pots, containers" },
    ],
  },
  {
    id: "finishing",
    title: "Finishing",
    tagline: "Surface treatments that protect and refine finished parts",
    description:
      "Finishing steps such as powder coating, painting, anodizing, and polishing give cut and fabricated parts a clean surface and lasting protection against wear and corrosion.",
    image: "/service-finishing.jpg",
    features: [
      "Powder coating in a range of finishes",
      "Painting and protective coatings",
      "Anodizing available on suitable metals",
      "Polishing for a smoother surface",
      "Improved resistance to corrosion",
      "Finishes that serve both looks and function",
    ],
    specs: [
      { label: "Processes", value: "Powder coating, painting, anodizing, polishing" },
      { label: "Purpose", value: "Appearance and durability improvement" },
      { label: "Output", value: "Finished and protected components" },
      { label: "Use Cases", value: "Industrial and fabricated metal products" },
    ],
  },
  {
    id: "stamping",
    title: "Stamping",
    tagline: "High-speed pressing of sheet metal parts in volume",
    description:
      "Stamping presses sheet metal into finished parts at high speed, making it well suited to large-volume work such as automotive body panels and appliance components.",
    image: "/service-stamping.png",
    features: [
      "High-speed pressing of sheet metal parts",
      "The same shape reproduced every stroke",
      "Built for mass-manufacturing demand",
      "Cost-effective on large production runs",
      "Suited to automotive body panels",
      "Handles appliance component work",
    ],
    specs: [
      { label: "Process", value: "Sheet metal stamping" },
      { label: "Production Type", value: "High-speed and high-volume" },
      { label: "Common Uses", value: "Automotive panels and appliance parts" },
      { label: "Output", value: "Stamped production components" },
    ],
  },
  {
    id: "punching",
    title: "Punching",
    tagline: "Punch press holes and cutouts for volume production",
    description:
      "Punching uses a punch press to form holes and shaped openings in sheet metal, making it a practical choice for high-volume production of parts that need repeated features.",
    image: "/service-punching.png",
    features: [
      "Holes and cutouts formed in sheet metal",
      "Worked on a punch press",
      "Highly repeatable across production runs",
      "Short cycle times on bulk orders",
      "Creates mounting and functional openings",
      "Well matched to mass production",
    ],
    specs: [
      { label: "Process", value: "Punch press machining" },
      { label: "Output", value: "Holes and shaped sheet features" },
      { label: "Production Fit", value: "Mass production" },
      { label: "Application", value: "Industrial sheet metal parts" },
    ],
  },
];
