export const contactFaqs = [
  {
    question: "How fast can you deliver a quote?",
    answer:
      "We aim to share quotes within 4 to 8 business hours for standard jobs. Send your DXF, DWG, STEP, IGES, or PDF drawings with material details for the fastest response.",
  },
  {
    question: "What file formats do you accept?",
    answer:
      "We accept DXF, DWG, STEP, IGES, PDF drawings, and hand-marked sketches. Our team reviews every submission for manufacturability before production.",
  },
  {
    question: "What is your minimum order quantity?",
    answer:
      "We support everything from one-off prototypes to repeat production batches, depending on the process, material, and delivery schedule.",
  },
  {
    question: "Do you offer on-site pickup?",
    answer:
      "Yes. You can arrange pickup from our Kamrej, Surat, Gujarat facility, and we can also coordinate dispatch across India.",
  },
] as const;

export const siteConfig = {
  name: "Balaji Engineering Works",
  legalName: "Balaji Engineering Works",
  shortName: "Balaji Engineering",
  alternateName: "Sheet Metal Bending Works",
  url:
    process.env.NEXT_PUBLIC_SITE_URL || "https://www.sheetmetallasercutting.com",
  ogImage: "/opengraph.jpg",
  description:
    "Balaji Engineering Works is a Surat-based manufacturer and service provider for CNC laser cutting services in Surat, CNC plasma cutting services in Surat, CNC plate bending service in Surat, sheet metal fabrication, and industrial products including base plates, foundation bolts, purlins, perforated sheets, and heavy fabrication.",
  phone: "+919978753398",
  phoneDisplay: "+91 99787 53398",
  email: "balajieng.works12@gmail.com",
  foundingDate: "2001",
  priceRange: "$$",
  gstNumber: "24BCUPS8314Q1ZK",
  businessType: "Manufacturer and Service Provider",
  locale: "en_IN",
  language: "en-IN",
  indiaMartProfile: "https://www.balajiengineeringworks.in/",
  serviceAreas: [
    "Surat",
    "Kamrej",
    "Bharuch",
    "Ankleshwar",
    "Vapi",
    "Vadodara",
    "Ahmedabad",
    "Gujarat",
    "Maharashtra",
    "Mumbai",
    "Rajasthan",
    "Madhya Pradesh",
    "India",
  ],
  industries: [
    "Sheet Metal Fabrication",
    "Sheet Metal Forming",
    "Sheet Metal Forming Industries Surat",
    "Structural Steel Fabrication",
    "CNC Laser Cutting",
    "CNC Plasma Cutting",
    "Steel Shearing",
    "Steel Plate Bending",
    "Press Brake Bending",
    "Plate Rolling",
    "Profile Cutting",
    "Steel Punching",
    "Heavy Fabrication",
    "Industrial Manufacturing",
    "Industrial Product Manufacturing",
    "Structural Steel Components",
  ],
  keywords: [
    // === BRAND ===
    "Balaji Engineering Works",
    "Balaji Engineering Works Surat",
    "balaji engineering surat",
    "balaji engineering gujarat",
    "balaji sheet metal works",
    // === CNC LASER CUTTING — PRIMARY FOCUS ===
    "CNC laser cutting",
    "CNC laser cutting service",
    "CNC laser cutting surat",
    "CNC laser cutting gujarat",
    "CNC laser cutting india",
    "CNC laser cutting near me",
    "CNC laser cutting company",
    "CNC laser cutting manufacturer",
    "CNC laser cutting supplier",
    "CNC laser cutting price",
    "CNC laser cutting cost",
    "CNC laser cutting rate",
    "CNC laser cutting rate per kg",
    "CNC laser cutting quote",
    "CNC laser cutting job work",
    "laser cutting service",
    "laser cutting works",
    "laser cutting surat",
    "laser cutting gujarat",
    "laser cutting india",
    "laser cutting near me",
    "laser cutting company",
    "laser cutting manufacturer",
    "laser cutting supplier",
    "laser cutting price",
    "laser cutting price per kg",
    "laser cutting price per meter",
    "laser cutting cost",
    "laser cutting rate",
    "laser cutting rate per kg",
    "laser cutting quote",
    "laser cutting job work",
    "fiber laser cutting",
    "fiber laser cutting service",
    "fiber laser cutting surat",
    "fiber laser cutting india",
    "fiber optic laser cutting",
    "fiber laser cutting company",
    "sheet metal laser cutting",
    "sheet metal laser cutting surat",
    "sheet metal laser cutting india",
    "metal laser cutting service",
    "steel laser cutting",
    "industrial laser cutting",
    "precision laser cutting",
    "precision laser cutting service",
    "precision laser cutting surat",
    "custom laser cutting",
    "custom laser cutting surat",
    "2D laser cutting",
    "laser sheet cutting",
    "laser plate cutting",
    "laser profile cutting",
    "DXF laser cutting",
    "DXF file laser cutting service",
    "MS laser cutting",
    "MS laser cutting surat",
    "SS laser cutting",
    "SS laser cutting surat",
    "aluminum laser cutting",
    "aluminium laser cutting surat",
    "mild steel laser cutting",
    "stainless steel laser cutting",
    "galvanized laser cutting",
    "HR plate laser cutting",
    "CRCA sheet laser cutting",
    // === CNC PLASMA CUTTING — SECONDARY FOCUS ===
    "CNC plasma cutting",
    "CNC plasma cutting service",
    "CNC plasma cutting surat",
    "CNC plasma cutting gujarat",
    "CNC plasma cutting india",
    "CNC plasma cutting near me",
    "CNC plasma cutting company",
    "CNC plasma cutting price",
    "CNC plasma cutting rate",
    "CNC plasma cutting job work",
    "plasma cutting service",
    "plasma cutting works",
    "plasma cutting surat",
    "plasma cutting gujarat",
    "plasma cutting india",
    "plasma cutting near me",
    "plasma cutting company",
    "plasma cutting price",
    "plasma cutting rate",
    "plasma cutting job work",
    "heavy plate plasma cutting",
    "thick plate plasma cutting",
    "MS plasma cutting",
    "MS plasma cutting surat",
    "structural plasma cutting",
    "plasma profile cutting",
    // === CNC BENDING ===
    "CNC press brake bending",
    "CNC press brake bending surat",
    "CNC press brake service",
    "press brake bending",
    "press brake bending service",
    "press brake bending surat",
    "press brake bending india",
    "CNC plate bending surat",
    "cnc plate bending service surat",
    "plate bending services surat",
    "sheet metal bending surat",
    "sheet bending service surat",
    "CNC bending surat",
    "plate bending price",
    "plate bending job work",
    // === PLATE ROLLING ===
    "plate rolling service",
    "plate rolling surat",
    "plate rolling india",
    "cylinder rolling service",
    "cone rolling service",
    "pipe rolling service",
    "pipe rolling surat",
    "shell rolling service",
    "tank shell rolling",
    "plate rolling and bending",
    // === PROFILE CUTTING ===
    "profile cutting service",
    "profile cutting surat",
    "CNC profile cutting",
    "laser profile cutting",
    "steel profile cutting",
    "flat bar cutting service",
    "angle cutting service",
    "channel cutting service",
    // === SHEET METAL FABRICATION ===
    "sheet metal fabrication",
    "sheet metal fabrication service",
    "sheet metal fabrication surat",
    "sheet metal fabrication gujarat",
    "sheet metal fabrication india",
    "sheet metal fabrication near me",
    "sheet metal fabrication company",
    "sheet metal fabrication manufacturer",
    "sheet metal fabrication supplier",
    "sheet metal fabrication price",
    "sheet metal fabrication cost",
    "sheet metal fabrication job work",
    "custom sheet metal fabrication",
    "precision sheet metal fabrication",
    "heavy sheet metal fabrication",
    "heavy fabrication surat",
    "heavy fabrication india",
    "industrial sheet metal fabrication",
    "structural sheet metal fabrication",
    "sheet metal parts manufacturer",
    "sheet metal components manufacturer",
    "sheet metal parts supplier",
    "sheet metal component supplier",
    "sheet metal forming service",
    "sheet metal shearing",
    "sheet metal cutting",
    "contract sheet metal fabrication",
    "outsource sheet metal fabrication",
    "B2B sheet metal fabrication",
    "bulk sheet metal fabrication",
    "prototype sheet metal fabrication",
    "STEP file fabrication",
    "DWG file metal fabrication",
    // === MATERIALS ===
    "MS laser cutting surat",
    "mild steel laser cutting surat",
    "mild steel plate bending service",
    "MS sheet cutting",
    "MS plate cutting",
    "MS fabrication surat",
    "stainless steel fabrication",
    "stainless steel sheet cutting",
    "stainless steel laser cutting surat",
    "stainless steel bending",
    "SS 304 laser cutting",
    "SS 316 laser cutting",
    "SS 202 fabrication",
    "SS laser cutting surat",
    "CRCA sheet laser cutting surat",
    "CRCA sheet fabrication",
    "HR plate cutting surat",
    "HR sheet fabrication",
    "hot rolled steel fabrication",
    "cold rolled steel fabrication",
    "galvanized sheet cutting surat",
    "GI sheet fabrication",
    "GI sheet cutting",
    "aluminum laser cutting surat",
    "aluminum sheet fabrication",
    "aluminium fabrication surat",
    "carbon steel fabrication",
    "structural steel fabrication",
    "high tensile steel fabrication",
    "boiler quality steel cutting",
    "pressure vessel steel fabrication",
    // === PRODUCTS — BASE PLATES ===
    "base plate manufacturer",
    "MS base plate manufacturer",
    "base plate manufacturer surat",
    "base plate manufacturer gujarat",
    "base plate manufacturer india",
    "MS base plate supplier",
    "base plate supplier surat",
    "laser cut base plate surat",
    "custom base plate fabrication",
    "column base plate manufacturer",
    "structural base plate manufacturer",
    "base plates for steel structures",
    "base plate wholesale surat",
    "base plate bulk order india",
    // === PRODUCTS — FOUNDATION BOLTS ===
    "foundation bolt manufacturer",
    "foundation bolt manufacturer surat",
    "foundation bolt manufacturer gujarat",
    "foundation bolt manufacturer india",
    "foundation bolt supplier surat",
    "foundation bolts wholesale",
    "MS foundation bolt manufacturer",
    "anchor bolt manufacturer surat",
    "anchor bolt supplier",
    "J type foundation bolt",
    "L type foundation bolt",
    "bent anchor bolt manufacturer",
    "custom foundation bolt",
    "foundation bolt price surat",
    "foundation bolt bulk order",
    "M20 foundation bolt",
    "M24 foundation bolt",
    "M30 foundation bolt",
    "M36 foundation bolt",
    // === PRODUCTS — PURLINS ===
    "purlin manufacturer surat",
    "purlin manufacturer gujarat",
    "purlin manufacturer india",
    "purlin supplier surat",
    "c purlin manufacturer surat",
    "z purlin manufacturer surat",
    "c and z purlin manufacturer surat",
    "steel purlin manufacturer",
    "MS purlin manufacturer",
    "roofing purlin manufacturer",
    "structural purlin manufacturer",
    "purlin for warehouse",
    "purlin for factory",
    "purlin for industrial building",
    "purlin price surat",
    "purlin wholesale india",
    "cold formed purlin",
    // === PRODUCTS — PERFORATED SHEETS ===
    "perforated sheet manufacturer surat",
    "perforated sheet manufacturer gujarat",
    "perforated sheet manufacturer india",
    "perforated sheet supplier surat",
    "MS perforated sheet manufacturer",
    "SS perforated sheet manufacturer",
    "laser cut perforated sheets",
    "custom perforated sheet",
    "perforated sheet price surat",
    "perforated sheet wholesale",
    "acoustic perforated sheet",
    "ventilation perforated sheet",
    "laser cut chequered plate",
    // === PRODUCTS — DECKING & ROOFING ===
    "decking sheet supplier surat",
    "decking sheet manufacturer surat",
    "floor decking sheet",
    "metal decking supplier",
    "corrugated sheet manufacturer surat",
    "corrugated roofing sheet surat",
    "corrugated metal sheet supplier",
    "GI corrugated sheet",
    "roofing sheet supplier surat",
    "industrial roofing sheet surat",
    // === PRODUCTS — STEEL PALLETS ===
    "steel pallet manufacturer surat",
    "steel pallet manufacturer gujarat",
    "MS pallet manufacturer surat",
    "metal pallet manufacturer",
    "industrial pallet manufacturer",
    "heavy duty steel pallet",
    "steel pallet wholesale",
    // === PRODUCTS — WALKWAY & STRUCTURAL ===
    "walkway plank manufacturer surat",
    "roof walkway plank",
    "steel walkway plank",
    "chequered plate cutting surat",
    "chequered plate supplier surat",
    "MS angle manufacturer surat",
    "MS channel manufacturer surat",
    "structural steel components surat",
    "steel structure fabrication surat",
    "conveyor stringer fabrication",
    "material handling fabrication",
    "industrial conveyor parts",
    // === INDUSTRIES SERVED ===
    "laser cutting for chemical industry",
    "laser cutting chemical plant",
    "laser cutting for petrochemical",
    "laser cutting for oil and gas",
    "laser cutting for pharma industry",
    "laser cutting for pharmaceutical plant",
    "laser cutting for food processing",
    "laser cutting for food industry",
    "automotive laser cutting",
    "automotive sheet metal fabrication",
    "laser cutting for automobile",
    "laser cutting for construction",
    "construction laser cutting surat",
    "laser cutting for power plant",
    "laser cutting for solar energy",
    "solar mounting frame laser cutting",
    "laser cutting for sugar industry",
    "laser cutting for textile industry",
    "laser cutting for cement industry",
    "laser cutting for mining",
    "laser cutting for warehouse",
    "laser cutting for industrial shed",
    "laser cutting for water treatment",
    "industrial laser cut components",
    "laser cut industrial parts",
    // === WELDING SERVICES ===
    "MIG welding fabrication",
    "MIG welding surat",
    "TIG welding fabrication",
    "TIG welding surat",
    "arc welding fabrication",
    "welding fabrication surat",
    "structural welding surat",
    "heavy welding fabrication",
    "steel welding fabrication",
    // === BUYER INTENT — PRICE & QUOTE ===
    "laser cutting price india",
    "plasma cutting price india",
    "sheet metal fabrication price india",
    "plate bending price india",
    "laser cutting cost india",
    "get a quote laser cutting",
    "free quote laser cutting surat",
    "laser cutting estimate",
    "laser cutting rate per kg",
    "laser cutting rate per meter",
    "plasma cutting rate per kg",
    "sheet metal bending rate per kg",
    "laser cutting price surat",
    "laser cutting price per kg surat",
    "plasma cutting price surat",
    "bulk laser cutting price",
    "contract laser cutting price",
    // === BUYER INTENT — SUPPLIER / MANUFACTURER ===
    "CNC laser cutting manufacturer india",
    "laser cutting supplier india",
    "laser cutting company india",
    "sheet metal fabrication manufacturer india",
    "steel fabricator india",
    "best laser cutting company india",
    "top laser cutting surat",
    "reliable laser cutting supplier india",
    "trusted CNC fabricator india",
    "laser cutting fabrication export",
    "export laser cut parts",
    "laser cut steel components export india",
    "laser cutting supplier surat",
    "steel fabricator surat",
    // === BUYER INTENT — JOB WORK & B2B ===
    "laser cutting job work",
    "laser cutting job work surat",
    "laser cutting job work india",
    "plasma cutting job work surat",
    "plasma cutting job work india",
    "sheet metal job work surat",
    "sheet metal job work india",
    "CNC job work surat",
    "CNC job work gujarat",
    "job work laser cutting surat",
    "job work fabrication india",
    "contract laser cutting manufacturing",
    "contract fabrication india",
    "outsource laser cutting india",
    "outsource sheet metal fabrication india",
    "B2B laser cutting india",
    "B2B sheet metal india",
    "bulk order laser cutting",
    "bulk order plasma cutting",
    "wholesale laser cutting service",
    "prototype laser cutting india",
    "small batch laser cutting",
    "large batch laser cutting",
    "custom CNC cutting service india",
    "DXF file laser cutting service",
    "DWG file laser cutting",
    "CAD drawing laser cutting",
    // === LOCATION — SURAT ===
    "sheet metal fabrication surat",
    "steel fabrication surat",
    "laser cutting surat",
    "plasma cutting surat",
    "plate bending surat",
    "press brake surat",
    "sheet metal works surat",
    "fabrication company surat",
    "metal works surat",
    "sheet metal near me surat",
    "sheet metal fabrication kamrej",
    "steel fabrication kamrej",
    // === LOCATION — GUJARAT ===
    "sheet metal fabrication gujarat",
    "steel fabrication gujarat",
    "laser cutting gujarat",
    "CNC laser cutting gujarat",
    "plasma cutting gujarat",
    "sheet metal supplier gujarat",
    "sheet metal manufacturer gujarat",
    "steel fabricator gujarat",
    "laser cutting bharuch",
    "sheet metal fabrication bharuch",
    "laser cutting ankleshwar",
    "CNC cutting ankleshwar",
    "laser cutting vapi",
    "sheet metal fabrication vapi",
    "laser cutting vadodara",
    "sheet metal fabrication vadodara",
    "steel fabrication vadodara",
    "laser cutting rajkot",
    "sheet metal fabrication ahmedabad",
    "laser cutting ahmedabad",
    "steel fabrication ahmedabad",
    // === LOCATION — MAHARASHTRA ===
    "sheet metal fabrication maharashtra",
    "sheet metal fabrication mumbai",
    "laser cutting mumbai",
    "steel fabrication mumbai",
    "sheet metal supplier mumbai",
    "sheet metal fabrication pune",
    "laser cutting pune",
    "sheet metal fabrication nashik",
    "sheet metal fabrication thane",
    // === LOCATION — INDIA ===
    "sheet metal fabrication india",
    "steel fabrication india",
    "laser cutting india",
    "plasma cutting india",
    "plate bending india",
    "sheet metal supplier india",
    "sheet metal manufacturer india",
    "pan india steel fabrication",
    "nationwide laser cutting supplier",
    "all india laser cutting supplier",
    "all india delivery fabrication",
    "heavy fabrication company india",
    // === WORLDWIDE / EXPORT ===
    "laser cutting export india",
    "laser cut parts export india",
    "custom laser cutting export",
    "B2B laser cutting worldwide",
    "laser cut parts supplier worldwide",
    "steel fabrication for export",
    "industrial laser cutting export india",
    "precision laser cut parts worldwide",
    "custom laser cut parts global",
    "steel component manufacturer india export",
    "sheet metal export from india",
    "laser cutting for global OEM",
    // === LONG-TAIL SEARCH PHRASES ===
    "CNC laser cutting service near me",
    "CNC plasma cutting service near me",
    "fiber laser cutting service near me",
    "best CNC laser cutting company surat",
    "fiber laser cutting company in gujarat",
    "industrial laser cutting company surat india",
    "MS base plate manufacturer in surat gujarat",
    "foundation bolt manufacturer in surat india",
    "c purlin z purlin manufacturer surat",
    "perforated sheet manufacturer in surat gujarat",
    "steel pallet manufacturer in surat gujarat",
    "custom laser cutting company india",
    "B2B laser cut parts supplier india",
    "laser cut sheet metal parts india",
    "laser cutting job work company surat",
    "CNC laser cutting and plasma cutting surat",
    "plate rolling and bending service surat",
    "structural steel fabrication company surat",
    "heavy fabrication company surat gujarat",
    "industrial laser cutting manufacturer surat",
    "steel components manufacturer surat gujarat",
    "quick turnaround laser cutting surat",
    "urgent laser cutting job work surat",
    "laser cut parts for construction india",
    "laser cut base plates for steel towers",
    "anchor bolts for buildings india",
    "purlins for warehouse roofing india",
    "perforated sheets laser cut filtration",
    "steel pallets for warehouse storage",
    "industrial laser cut components manufacturer india",
    "custom laser cut metal parts india",
    "laser cutting for OEM manufacturers india",
    "laser cut sheet metal components for OEM",
    "precision CNC laser cutting surat india",
    "get quote laser cutting fabrication india",
    "bulk laser cutting order india",
    "contract laser cutting manufacturer surat",
    "laser cutting for chemical and pharma plants",
    "laser cutting for automotive components india",
    "fiber laser cutting for precision parts",
    "DXF file laser cutting job work surat",
    "sheet metal laser cutting works surat gujarat",
  ],
  address: {
    streetAddress:
      "Kamrej, Surat, Gujarat",
    locality: "Surat",
    region: "Gujarat",
    postalCode: "394185",
    country: "IN",
  },
  mapUrl:
    "https://maps.google.com/?q=Balaji+Engineering+Works+Plot+No.+11+12+Soham+Industrial+Estate+NH+8+Kamrej+Surat+Gujarat+394185",
} as const;
