export const contactFaqs = [
  {
    question: "How fast can you deliver a quote?",
    answer:
      "We aim to share quotes within 4 to 8 business hours for standard jobs. Send your DXF, DWG, STEP, IGES, or PDF drawings with material details for the fastest response.",
  },
  {
    question: "What file formats do you accept?",
    answer:
      "We accept DXF, DWG, STEP, IGES, PDF drawings, and hand-marked sketches. Our team reviews every submission for manufacturability before production.",
  },
  {
    question: "What is your minimum order quantity?",
    answer:
      "We support everything from one-off prototypes to repeat production batches, depending on the process, material, and delivery schedule.",
  },
  {
    question: "Do you offer on-site pickup?",
    answer:
      "Yes. You can arrange pickup from our Kamrej, Surat, Gujarat facility, and we can also coordinate dispatch across India.",
  },
] as const;

export const siteConfig = {
  name: "Balaji Engineering Works",
  legalName: "Balaji Engineering Works",
  shortName: "Balaji Engineering",
  alternateName: "Sheet Metal Bending Works",
  url:
    process.env.NEXT_PUBLIC_SITE_URL || "https://sheetmetallasercutting.com",
  ogImage: "/opengraph.jpg",
  description:
    "Balaji Engineering Works is a Surat-based manufacturer and service provider for CNC laser cutting services in Surat, CNC plasma cutting services in Surat, CNC plate bending service in Surat, sheet metal fabrication, and industrial products including base plates, foundation bolts, purlins, perforated sheets, and heavy fabrication.",
  phone: "+919978753398",
  phoneDisplay: "+91 99787 53398",
  email: "balajieng.works12@gmail.com",
  foundingDate: "2001",
  priceRange: "$$",
  gstNumber: "24BCUPS8314Q1ZK",
  businessType: "Manufacturer and Service Provider",
  locale: "en_IN",
  language: "en-IN",
  indiaMartProfile: "https://www.balajiengineeringworks.in/",
  serviceAreas: [
    "Surat",
    "Gujarat",
    "Maharashtra",
    "Rajasthan",
    "Madhya Pradesh",
    "India",
  ],
  industries: [
    "Sheet Metal Fabrication",
    "Sheet Metal Forming",
    "Sheet Metal Forming Industries Surat",
    "Structural Steel Fabrication",
    "CNC Laser Cutting",
    "CNC Plasma Cutting",
    "Steel Shearing",
    "Steel Plate Bending",
    "Press Brake Bending",
    "Plate Rolling",
    "Profile Cutting",
    "Steel Punching",
    "Heavy Fabrication",
    "Industrial Manufacturing",
    "Industrial Product Manufacturing",
    "Structural Steel Components",
  ],
  keywords: [
    "Balaji Engineering Works",
    "Balaji Engineering Works Surat",
    "cnc laser cutting services surat",
    "cnc plasma cutting services surat",
    "cnc plate bending service surat",
    "sheet metal fabrication Surat",
    "sheet metal bending Surat",
    "sheet metal cutting and bending services surat",
    "sheet metal forming industries surat",
    "sheet bending service Surat",
    "cnc press brake bending surat",
    "press brake bending services surat",
    "cnc bending surat",
    "laser cutting services in surat",
    "CNC laser cutting Surat",
    "CNC plasma cutting Surat",
    "steel cutting services Surat",
    "sheet metal shearing cutting Surat",
    "plate bending services Surat",
    "plate rolling bending services",
    "plate profile cutting service Surat",
    "sheet metal cutting service Surat",
    "heavy fabrication Surat",
    "manufacturer and service provider Surat",
    "steel fabrication Gujarat",
    "mild steel plate bending service",
    "industrial steel plate cutting service",
    "stainless steel sheet cutting service",
    "CNC plasma cutting services",
    "MS base plates manufacturer",
    "base plate manufacturer surat",
    "ms base plate manufacturer surat",
    "foundation bolt manufacturer Surat",
    "foundation bolts manufacturers surat",
    "gutters manufacturer Surat",
    "z purlin manufacturer Surat",
    "c purlin manufacturer Surat",
    "c and z purlin manufacturer surat",
    "perforated sheets manufacturer Surat",
    "perforated sheet manufacturer surat",
    "decking sheets supplier Surat",
    "decking sheet supplier surat",
    "corrugated roofing sheets surat",
    "corrugated metal sheets supplier surat",
    "walkway plank manufacturer Surat",
    "roof walkway plank manufacturer",
    "steel pallets manufacturer Surat",
    "ms pallets manufacturer surat",
    "conveyor stringer fabrication",
    "Balaji Engineering Works",
    "custom steel fabrication",
    "industrial metal cutting",
    "laser cutting Gujarat",
    "heavy fabrication company India",
  ],
  address: {
    streetAddress:
      "Kamrej, Surat, Gujarat",
    locality: "Surat",
    region: "Gujarat",
    postalCode: "394185",
    country: "IN",
  },
  mapUrl:
    "https://maps.google.com/?q=Balaji+Engineering+Works+Plot+No.+11+12+Soham+Industrial+Estate+NH+8+Kamrej+Surat+Gujarat+394185",
} as const;
